name: Build and deploy ASP.Net Core app to Azure Web App - Items-API-

on:
  push:
    branches:
      - deploy-items-api
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build Items-API/Items-API.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish Items-API/Items-API.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C82B77BA387B40E0BE6BC139D8DDDF34 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_83C4BD26F68B4605B563338AAA33ED74 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0953DF7051D740FF8DBF01A735A86CF8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Items-API-'
          slot-name: 'Production'
          package: .